# Generated by Django 4.2.11 on 2024-04-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='image_url',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
